<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina evaluate">
    <link rel="shortcut icon" href="<?php echo $this->baseUrl("img/favicon.png")?>">

    <title>Flatlab</title>

    <!-- Bootstrap core CSS -->
    <link href="<?php echo $this->baseUrl("css/bootstrap.min.css")?>" rel="stylesheet">
    <link href="<?php echo $this->baseUrl("css/bootstrap-reset.css")?>" rel="stylesheet">
    <!--external css-->
    <link href="<?php echo $this->baseUrl("assets/font-awesome/css/font-awesome.css")?>" rel="stylesheet" />
    <link href="<?php echo $this->baseUrl("assets/jquery-file-upload/css/jquery.fileupload-ui.css")?>" rel="stylesheet" type="text/css" >
    <!-- Custom styles for this template -->
    <link href="<?php echo $this->baseUrl("css/style.css")?>" rel="stylesheet">
    <link href="<?php echo $this->baseUrl("css/style-responsive.css")?>" rel="stylesheet" />
    
    <!-- Evaluate styles for this template -->
    <link href="<?php echo $this->baseUrl("css/evaluation/style.css");?>" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
    <!--[if lt IE 9]>
      <script src="<?php echo $this->baseUrl("js/html5shiv.js");?>"></script>
      <script src="<?php echo $this->baseUrl("js/respond.min.js")?>"></script>
    <![endif]-->
  </head>

  <body>

  	<section id="container" class="">
  
		<!--header start-->
      	<?php echo $this->partial('layout/header.phtml');?>
      	<!--header end-->
      
      	<!--sidebar start--><!--left menu-->
      	<?php echo $this->partial('layout/sidebar.phtml');?>
      	<!--sidebar end-->
      
      	<!--main content start-->
      	<section id="main-content">
          
          	<!-- Content -->
          	<?php //echo '<pre>' . print_r($this, 1) . '</pre>';exit;?>
          	<?php echo $this->layout()->content;?>
          	
      	</section>
      	<!--main content end-->
      
      <!--footer start-->
      <?php echo $this->partial('layout/footer.phtml');?>
      <!--footer end-->
      
  	</section>

    <!-- js placed at the end of the document so the pages load faster -->
    <script src="<?php echo $this->baseUrl("js/jquery.js")?>"></script>
    <script src="<?php echo $this->baseUrl("js/bootstrap.min.js")?>"></script>
    <script src="<?php echo $this->baseUrl("js/jquery.dcjqaccordion.2.7.js")?>" type="text/javascript" class="include"></script>
    <script src="<?php echo $this->baseUrl("js/jquery.scrollTo.min.js")?>"></script>
    <script src="<?php echo $this->baseUrl("js/jquery.nicescroll.js")?>" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl("js/respond.min.js")?>" ></script>

	<!-- BEGIN:File Upload Plugin JS files-->
	<script src="<?php echo $this->baseUrl("assets/jquery-file-upload/js/vendor/jquery.ui.widget.js")?>"></script>
	<!-- The Templates plugin is included to render the upload/download listings -->
	<script src="<?php echo $this->baseUrl("assets/jquery-file-upload/js/vendor/tmpl.min.js")?>"></script>
	<!-- The Load Image plugin is included for the preview images and image resizing functionality -->
	<script src="<?php echo $this->baseUrl("assets/jquery-file-upload/js/vendor/load-image.min.js")?>"></script>
	<!-- The Canvas to Blob plugin is included for image resizing functionality -->
	<script src="<?php echo $this->baseUrl("assets/jquery-file-upload/js/vendor/canvas-to-blob.min.js")?>"></script>
	<!-- The Iframe Transport is required for browsers without support for XHR file uploads -->
	<script src="<?php echo $this->baseUrl("assets/jquery-file-upload/js/jquery.iframe-transport.js")?>"></script>
	<!-- The basic File Upload plugin -->
	<script src="<?php echo $this->baseUrl("assets/jquery-file-upload/js/jquery.fileupload.js")?>"></script>
	<!-- The File Upload file processing plugin -->
	<script src="<?php echo $this->baseUrl("assets/jquery-file-upload/js/jquery.fileupload-fp.js")?>"></script>
	<!-- The File Upload user interface plugin -->
	<script src="<?php echo $this->baseUrl("assets/jquery-file-upload/js/jquery.fileupload-ui.js")?>"></script>

    <!--common script for all pages-->
    <script src="<?php echo $this->baseUrl("js/common-scripts.js")?>"></script>


  </body>
  
</html>
