<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina, Evaluation">
    <link rel="shortcut icon" href="img/favicon.png">

    <title>FlatLab - Flat & Responsive Bootstrap Admin Template</title>
<?php //echo '<pre>' . print_r(APP_URL, 1). '</pre>'; ?>
    <!-- Bootstrap core CSS -->
<?php echo $this->baseUrl(); ?>
	<link href="<?php echo $this->baseUrl("css/bootstrap.min.css"); ?>" rel="stylesheet">
    <link href="<?php echo $this->baseUrl("css/bootstrap-reset.css");?>" rel="stylesheet">
    <!--external css-->
    <link href="<?php echo $this->baseUrl("assets/font-awesome/css/font-awesome.css");?>" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="<?php echo $this->baseUrl("css/style.css");?>" rel="stylesheet">
    <link href="<?php echo $this->baseUrl("css/style-responsive.css");?>" rel="stylesheet" />
    <!-- Evaluate styles for this template -->
    <link href="<?php echo $this->baseUrl("css/evaluation/style.css");?>" rel="stylesheet">
	
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
    <!--[if lt IE 9]>
    <script src="<?php echo $this->baseUrl("js/html5shiv.js");?>"></script>
    <script src="<?php echo $this->baseUrl("js/respond.min.js");?>"></script>
    <![endif]-->
</head>

  <body class="login-body">

    <div class="container">

      <form class="form-signin" action="index.html">
        <h2 class="form-signin-heading">sign in now</h2>
        <div class="login-wrap">
            <input type="text" class="form-control" name="username"  placeholder="Username" autofocus>
            <input type="password" class="form-control" name="password" placeholder="Password">
            <label class="checkbox">
                <input type="checkbox" value="remember-me"> Remember me
                <span class="pull-right">
                    <a data-toggle="modal" href="#myModal"> Forgot Password?</a>

                </span>
            </label>
            <button class="btn btn-lg btn-login btn-block" type="button">Sign in</button>
            

        </div>

          <!-- Modal -->
          <div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="myModal" class="modal fade">
              <div class="modal-dialog">
                  <div class="modal-content">
                      <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                          <h4 class="modal-title">Forgot Password ?</h4>
                      </div>
                      <div class="modal-body">
                          <p>Enter your e-mail address below to reset your password.</p>
                          <input type="text" name="email" placeholder="Email" autocomplete="off" class="form-control placeholder-no-fix">

                      </div>
                      <div class="modal-footer">
                          <button data-dismiss="modal" class="btn btn-default" type="button">Cancel</button>
                          <button class="btn btn-success" type="button">Submit</button>
                      </div>
                  </div>
              </div>
          </div>
          <!-- modal -->

      </form>

    </div>

    <!-- js placed at the end of the document so the pages load faster -->
    <script src="<?php echo $this->baseUrl("js/jquery.js");?>"></script>
    <script src="<?php echo $this->baseUrl("js/bootstrap.min.js");?>"></script>
    
    <!-- script src="<?php //echo APP_URL?>application/modules/systemapi/templates/default/js/shared.js"></script-->
    
    
    <script type="text/javascript">

    $(document).ready(function(){
    		//$(".btn-login").on("click", checkLogin, false);
    	$(".btn-login").on("click", function(){
				console.log('click');
				checkLogin();
    	});
    });

    function checkLogin(){
    	var vChk;
    	var user = $( "input[name='username']" ).val();
    	var pwd = $( "input[name='password']" ).val();
    	var projectName = '<?php echo projectName; ?>';
    	//var chk = document.getElementById('f_remem').checked;

    	if(user =='' || pwd =='' ){
    		_alert('Pleses input Username and password.');
    	}else{
    		var baseUrl = '/authen/index/login';

    		//if(chk == true) vChk = 'Y';else vChk = 'N';
    		$.ajax({
    			type: "POST",
    			url: baseUrl,
    			data: {username:user,password:pwd,remember:vChk},
    			success: function(msg){

//     				eval(msg);
					if(msg == "success") {
    					window.location.href = '/workflow/index/portal';
					}
					else {
						alert('Username or Password not valid.');
						return false;
					}
    			}
    		});
    	}
    }
    	  	
    
    
    </script>

  </body>
</html>
